apiVersion: v1
kind: Service
metadata:
  name: aceessfitness-service
spec:
  # NodePort type exposes the service on a port across all cluster nodes (Minikube).
  type: NodePort 
  
  # Selects the Pods to route traffic to (must match the Deployment's Pod labels)
  selector:
    app: aceessfitness
    tier: frontend
  ports:
    - protocol: TCP
      # The port the service itself is exposed on (e.g., 5000)
      port: 5000
      
      # The port the Service forwards traffic to inside the container (must match containerPort)
      targetPort: 5000 
      
      # Optional: Explicitly set the node port
      # nodePort: 30080