name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or your desired branch
    tags:
      - 'v*.*.*' # Matches tags like v1.0.0, v2.3.4, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set Image Tag
        id: set_tag
        run: |
          # 1. Check if the trigger was a Git Tag push
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            # Use the tag name directly (e.g., v1.0.0)
            VERSION=${{ github.ref_name }}
          else
            # If not a tag push (e.g., push to 'main'), use a default tag or commit SHA
            VERSION=sha-${GITHUB_SHA::7}
          fi
          
          # Output the determined version to be used in subsequent steps
          
          echo "DOCKER_IMAGE_TAG=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:${{ steps.set_tag.outputs.DOCKER_IMAGE_TAG }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-image:${{ steps.set_tag.outputs.DOCKER_IMAGE_TAG }}
